package main

/**
log.Panicln() is recoverable and still runs deferred functions
log.Fatalln() exists program
*/
func main() {
	error_info()
}
